spring:

  application:
    name: r2dbc-coroutines-demo

  r2dbc:
    url: r2dbc:postgresql://localhost:15433/postgres
    username: postgres
    password: secret

  flyway:
    url: jdbc:postgresql://localhost:15433/postgres
    user: postgres
    password: secret
    baseline-on-migrate: true

outbox:
  publish:
    interval: PT1S